let name = "Anas Shaikh";
let school = "Masai School";
let grade = "A++";
let section = "A";
 let rollNo = 30;
let physicsMark = 100;
let chemistryMark = 100;
let biologyMark = 100;

console.log("<><><><><><><><><><><><><><><><><><>");
console.log("<>                                <>");
console.log("<>                                <>");
console.log("<>           REPORT CARD          <>");
console.log("<>                                <>");
console.log("<>        Name : "+name+"      <>");
console.log("<>                                <>");
console.log("<>       School : "+school+"    <>");
console.log("<>                                <>");
console.log("<>          Grade : "+grade+"           <>");
console.log("<>                                <>");
console.log("<>           Section : "+section+"          <>");
console.log("<>                                <>");
console.log("<>          Roll No : "+rollNo+"          <>");
console.log("<>                                <>");
console.log("<>       Physics Marks : "+physicsMark+"      <>");
console.log("<>                                <>");
console.log("<>      Chemistry Marks : "+chemistryMark+"     <>");
console.log("<>                                <>");
console.log("<>       Biology Marks : "+biologyMark+"      <>");
console.log("<>                                <>");
console.log("<>                                <>");
console.log("<><><><><><><><><><><><><><><><><><>");
